### ISSUE TITLE
Agent setup steps typo: Requiered => Required

### ISSUE THREAD

**Issue by eric-blue** [relative-ci/agent#183]
https://relative-ci.com/documentation/setup/webpack-plugin

<img width="743" alt="Screen Shot 2020-12-17 at 3 18 03 PM" src="https://user-images.githubusercontent.com/19786312/102555204-2cb2c300-407b-11eb-985c-a02e49dcc8ba.png">

**Comment by vio** [comment]
Thank you @eric-blue, fixed! 🙇
