### ISSUE TITLE
Trouble with setup/getting first bundle stat reading

### ISSUE THREAD

**Issue by eric-blue** [relative-ci/agent#191]
Apologies if this is not the place for this. I have been trying to get my solution setup with rci, but am hitting a wall. 

The track I followed to setup:
- `npm install --save-dev @relative-ci/agent`
- [configure](RelativeCiAgentWebpackPlugin) `RelativeCiAgentWebpackPlugin`
- configure `RELATIVE_CI_KEY` in our circle-ci

and after all that I can see this output in my pipeline:
 ```
 Running "webpack:prod" (webpack) task
  relative-ci:agent {
  relative-ci:agent   includeCommitMessage: true,
  relative-ci:agent   stats: {
  relative-ci:agent     context: '/root/project/static/compiled/scripts/webpack-stats.json',
  relative-ci:agent     assets: true,
  relative-ci:agent     entrypoints: true,
  relative-ci:agent     chunks: true,
  relative-ci:agent     modules: true
  relative-ci:agent   },
  relative-ci:agent   enabled: '1'
  relative-ci:agent } +0ms
  ```
  and then
  ```
  RelativeCiAgentInvalid webpack stats structure, please make sure webpack stats configuration is correct
  ```
  
 this leads me to believe it is working, but no stats are being displayed on the relative-ci dashboard and no additional logging is available. 
  
  A few things about this project:
  - multiple entry files
  - webpack-stats is output into the dir `'static/compiled/scripts/webpack-stats.json'`

**Comment by vio** [comment]
Hi @eric-blue, thanks for the report!

Based on the error, the webpack stats file is not passing the [validation](https://github.com/relative-ci/bundle-stats/blob/master/packages/utils/src/webpack/struct.js). If possible, can you please provide more details about your setup?
1. Webpack version
2. webpack-plugin or the cli setup?
3. full error message - after `Invalid webpack stats structure, please make sure webpack stats configuration is correct` there should be a `Expected a value of type ...`
4. webpack stats source (if you can't share it publicly, you can send it directly to me via email - see github profile)

**Comment by eric-blue** [comment]
hey @vio thanks for getting back so quick. One thing to note is that my project consists of many bundle entries

1.  webpack `5.11.1`
2. webpack-plugin setup
3. `Expected a value of type 'interface<{id,entry,initial,names,files}>[] | undefined' for 'chunks'`
4. webpack stats source has been sent

**Comment by vio** [comment]
Thanks! The webpack stats is incomplete, I wanted to verify if there are any _invalid_ chunk entries, but the array is cropped. Can you please try to generate it again? You can also try to validate it yourself with `npx bundle-stats webpack-stats.json`.

Also, will be helpful if you can share your `@relative-ci/agent` config in case you have something a bit more custom, i noticed in your logs that context is wrongly set to the webpack stats filepath (it should be a directory - https://webpack.js.org/configuration/stats/#statscontext)

**Comment by eric-blue** [comment]
Apologies, after running `npm cache clean --force` i was able to rerun and get a better stats.json, (sent to your email)

here is the plugin config
```
    new RelativeCiAgentWebpackPlugin({
      stats: {
        context: path.resolve(__dirname, "static/compiled/scripts/"),
        assets: true,
        entrypoints: true,
        chunks: true,
        modules: true
      }
    }),
```

> i noticed in your logs that context is wrongly set to the webpack stats filepath

thanks for catching that!

and after running `npx bundle-stats static/compiled/scripts/stats.json`:
```
  ✖ Read Webpack stats files
    → Filepath: static/compiled/scripts/stats.json
    Read baseline data
    Write baseline data
    Process data
    Generate reports
    Save reports
Invalid webpack stats structure, please make sure webpack stats configuration is correct.

Expected a value of type `interface<{id,entry,initial,names,files}>[] | undefined` for `chunks`
https://github.com/relative-ci/bundle-stats/tree/master/packages/cli#webpack-configuration
Filepath: static/compiled/scripts/stats.json
```

**Comment by eric-blue** [comment]
i should mention that i am using the ______ plugin to generate the stats as it was pre-existing in my env

```
  plugins: [
    ...
    new BundleAnalyzerPlugin({
      analyzerMode: "disabled",
      generateStatsFile: true,
    }),
    new RelativeCiAgentWebpackPlugin({
      stats: {
        context: path.resolve(__dirname, "static/compiled/scripts/"),
        assets: true,
        entrypoints: true,
        chunks: true,
        modules: true
      }
    }),
  ],
```

**Comment by vio** [comment]
> here is the plugin config

Couple notes about your config:
- `context` - should point to your source folder to help webpack trim the absolute paths in the report
- you can probably remove the options, they are set by default by the plugin (set only context if you don't have it at the app level)

However, I don't think the config is the main cause for your error. Since webpack v5, some of the stats properties can contain groups of entries (eg: https://webpack.js.org/configuration/stats/#statschunkgroups) and the validation can fail. If you can resend the full webpack-stats.json, I will try to have another look at the structure.

**Comment by eric-blue** [comment]
> If you can resend the full webpack-stats.json, I will try to have another look at the structure.

Forgot to hit send before. Sent now!

**Comment by vio** [comment]
@eric-blue Thank you for sharing the webpack stats! Since v5, webpack can output different type of entries for assets, chunks and modules based on [stats](https://github.com/relative-ci/bundle-stats/commit/3db759832c7b02c5d48a20ee817eb2620ef0e84f) [config](https://github.com/relative-ci/bundle-stats/commit/4861396a0dd98ae7e9e144ba04e0ef5beb6072fc). Since their structure is different than what we expect, the validation is failing.

I fixed the validator to allow and filter the different entry types (`@relative-ci/agent@1.5.0-beta.2`). If you get to try it, let me know how is going ;)

**Comment by eric-blue** [comment]
that did it! Just a slight issue on my end interpolating the api key and then I should be ready to go. Thanks for all your help on this @vio. Excited to start using the tool!

**Comment by eric-blue** [comment]
spoke too soon. I'm seeing this now in response from the server:

```
relative-ci:agent Response { code: 'InternalServer', message: 'Sorry, something went wrong.' }
```

**Comment by eric-blue** [comment]
@vio whatever you did worked, the POST went through!

However now I am seeing this, do you know why that might be?:

![Screen Shot 2021-01-08 at 12 40 49 PM](https://user-images.githubusercontent.com/19786312/104062157-c8cd7700-51ae-11eb-8975-12c693739414.png)

commit is registered, but no bundle stats are reading

**Comment by vio** [comment]
@eric-blue `Summary` is showing data for the project `baseBranch` (eg: `master`). Your first job is in a different branch, so no data to show ;) If you click on the job number, you can view the job report.

**Comment by eric-blue** [comment]
🤦 

Thanks again for all your help @vio

**Comment by vio** [comment]
No problem, thanks again for sharing the webpack stats and for your patience ! ;)
