### ISSUE TITLE
Error showing in jsconfig.json

### ISSUE THREAD

**Issue by Nyazuki** [relative-ci/agent#200]
Can someone fix the error showing in the jsconfig.json?
https://github.com/relative-ci/agent/blob/baf4d1f1262dc6b38f137a543cd665ff3a840ba6/jsconfig.json#L5

`node` is not a valid option here.
![Screen Shot 2021-01-19 at 9 24 14 AM](https://user-images.githubusercontent.com/20983354/105055814-79eecf80-5a41-11eb-928a-502603e9f400.png)

**Comment by vio** [comment]
Thank you @Nyazuki, fixed by https://github.com/relative-ci/agent/commit/cc93c41e52487b9efc4dd6452d63e5941a6cd97b.

Out of curiosity, in what case are you getting this warning?

**Comment by Nyazuki** [comment]
> Thank you @Nyazuki, fixed by [cc93c41](https://github.com/relative-ci/agent/commit/cc93c41e52487b9efc4dd6452d63e5941a6cd97b).
> 
> Out of curiosity, in what case are you getting this warning?

I belive the three error messages showing in the screenshot are from ESLint server, Typescript server, and Node server which is either build-in on my VS code, or added in as extension. The one from Node will show after the build is done in runtime.

Thanks for the fix!
