### ISSUE TITLE
regen api key

### ISSUE THREAD

**Issue by eric-blue** [relative-ci/agent#289]
We've recently had a breach on our end of our API keys. It would be awesome if relative-ci had the ability to regenerate the key for `RELATIVE_CI_KEY`

**Comment by vio** [comment]
@eric-blue you can't regenerate the key atm from the project admin, but I can do it for you. Just let me know when is ok to do it.

**Comment by eric-blue** [comment]
sooner the better, thanks!

**Comment by vio** [comment]
@eric-blue updated, you can copy the new key from your project settings
