### ISSUE TITLE
error when building @relative-ci/agent library

### ISSUE THREAD

**Issue by Nigui** [relative-ci/agent#328]
Hello, 
I can't use your product because of an error at build time. 

I have imported `@relative-ci/agent` into my webpack config file then it broke the build with the following error:

`You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer`

Could you help ? 
Thank you

**Comment by vio** [comment]
Hi @Nigui! `@relative-ci/agent` doesn't rely directly on the source map consumer, most likely the error is happening upstream. Can you share more details about your setup:

- full stack error
- webpack version
- agent version / setup
- node version?

**Comment by Nigui** [comment]
- webpack `4.43`
- @relative-ci/agent `1.5.0`
- node `v12.17`

I don't have more lines on stack trace, except the one above. Sorry.

**Comment by vio** [comment]
Thanks for sharing @Nigui! I'm pretty sure there are a bunch of projects that are using `1.5.0` with webpack 4 and node 12. I will try to replicate the exact versions. 

Searches for the same error message ended up on https://github.com/mozilla/source-map/issues/349.

Also, if you are able to try on your setup:
1. use the latest version - `@relative-ci/agent@1.6.1`
2. disable source maps (no `devtool`)
