### ISSUE TITLE
Don't throw on errors?

### ISSUE THREAD

**Issue by rohit-gohri** [relative-ci/agent#33]
I was trying this out with a gatsby site hosted at Netlify. But env-ci doesn't support Netlify(https://github.com/pvdlg/env-ci/issues/125) and the build failed. I had added the RELATIVE_CI_SLUG key but for some reason getting the branch from git metadata failed, could be the way netlify clones the repo.

Instead of my build failing because of that, wouldn't it be better if we let the build continue and instead don't send any stats as sending a stats report isn't vital to the build.

We could send a mail alert, or log errors during the build.

**Comment by vio** [comment]
hi @rohit-gohri, thanks for opening a ticket for the missing env-ci service! 

> Instead of my build failing because of that, wouldn't it be better if we let the build continue and instead don't send any stats as sending a stats report isn't vital to the build.
Agree, the agent should not throw, but just show a warning.

**Comment by vio** [comment]
@rohit-gohri You can try to use `@relative-ci/agent@v1.3.0-beta.4`.

Regarding env-ci support for Netlify, I subscribed to the ticket and will update the dependency once it will be updated. 

In the meantime, I am considering forking and releasing `@relative-ci/env-ci` with Netlify support (if you do have the PR ready, will be more than happy to merge it).

Another temporary option is to map Netlify env variables to an existing services, here is an example for Now:
```js
// now.js
if (process.env.NOW_BUILDER) {
  process.env.CI = true;
  process.env.CIRCLECI = true;
  process.env.CIRCLE_BRANCH = process.env.NOW_GITHUB_COMMIT_REF;
  process.env.CIRCLE_SHA1 = process.env.NOW_GITHUB_COMMIT_SHA;
  process.env.CIRCLE_PROJECT_REPONAME = process.env.NOW_GITHUB_COMMIT_REPO;
  process.env.CIRCLE_PROJECT_USERNAME = process.env.NOW_GITHUB_COMMIT_ORG;
}
```

**Comment by rohit-gohri** [comment]
> @rohit-gohri You can try to use `@relative-ci/agent@v1.3.0-beta.4`.

Will do. That was fast :+1: 

> In the meantime, I am considering forking and releasing `@relative-ci/env-ci` with Netlify support (if you do have the PR ready, will be more than happy to merge it).

I'll be able to do it by tomorrow :sweat_smile:

**Comment by rohit-gohri** [comment]
> > In the meantime, I am considering forking and releasing `@relative-ci/env-ci` with Netlify support (if you do have the PR ready, will be more than happy to merge it).
> 
> I'll be able to do it by tomorrow sweat_smile


:sweat_smile: https://github.com/pvdlg/env-ci/pull/126

You can pull the changes from here : https://github.com/rohit-gohri/env-ci/tree/netlify
Or let's just wait if env-ci one get's merged

**Comment by rohit-gohri** [comment]
> @rohit-gohri You can try to use `@relative-ci/agent@v1.3.0-beta.4`.
> 

Warnings worked correctly:
```
warning ERROR: "branch" environment variable is missing, make sure the agent is setup correctly! Read more about RelativeCI agent setup at https://relative-ci.com/documentation/setup.
```

**Comment by rohit-gohri** [comment]
I used patch-package to test https://github.com/pvdlg/env-ci/pull/126 and it works: https://app.relative-ci.com/projects/kki0Wz9wbvGQVMX73Tjc/jobs/1-d4edd437-dd7f-4857-9811-f38619a00620 :tada:

**Comment by vio** [comment]
Amazing 👏 

In the meantime I released `@relative-ci/agent@1.3.0-beta.5` with a dependency to https://github.com/relative-ci/env-ci

**Comment by vio** [comment]
@rohit-gohri missed to update the import, please use `1.3.0-beta.6`.

**Comment by rohit-gohri** [comment]
Great! Closing the issue as the main problem of errors is fixed 😄
