### ISSUE TITLE
Propagate args from Webpack plugin

### ISSUE THREAD

**Issue by gjsduarte** [relative-ci/agent#469]
Currently it is not possible to send arguments to the `agent` from the Webpack plugin: 

https://github.com/relative-ci/agent/blob/d50a44d8a8512fcdde849d8129e375b61871a4b8/src/webpack-plugin.js#L40

This invalidates passing options to the agent to allow passing env variables not detected by `env-ci`.

I would be nice if you could allow passing the `args` object from the Webpack plugin constructor parameters and thus allowing manually specifying CI variables

**Comment by vio** [comment]
Thanks @gjsduarte! The CLI is already allowing overrides via arguments, i think will make a lot of sense to allow it for the webpack plugin as well.

Did you encounter problems with any of the env-ci variables?

**Comment by gjsduarte** [comment]
Yes, We're running builds out of Vercel, which doesn't expose a PR number environment variable.

We do collect the PR number using another method and would like to forward this to relative-ci to enable PR status comments

**Comment by vio** [comment]
> We do collect the PR number using another method and would like to forward this to relative-ci to enable PR status comments
Can you share what method you are using? Maybe we can add the same method [upstream](https://github.com/semantic-release/env-ci/pull/140)?

> We're running builds out of Vercel, which doesn't expose a PR number environment variable.
For specific CI providers, RelativeCI is using the GitHub api to get the corresponding PR based on sha when the agent is not providing one. I added `vercel` to the list as well ;)

**Comment by gjsduarte** [comment]
We're collecting the Github PR number using https://github.com/useparcel/vercel-is-pull-request

But if you're already collecting the PR from the GitHub api already, then this might be redundant.
I'll give it a test with the latest version when you release a bump to `env-ci` to if it's still needed

**Comment by vio** [comment]
Thanks for sharing @gjsduarte!

If you are using it with @relative-ci/agent to send the pr number, is not necessary anymore. RelativeCI picks up the corresponding pr number for vercel builds using [octokit.js](https://octokit.github.io/rest.js/v18) `listPullRequestsAssociatedWithCommit`.
